input-output-hk/cardano-explorer-app

- CHANGELOG.md
- package.json
- yarn.lock
This PR upgrades **lodash** to its `4.17.13` version. The version currently used has a vulnerability of critical severity level:
`critical severity`
**Vulnerable versions:** < 4.17.13
**Patched version:** 4.17.13
Affected versions of lodash are vulnerable to Prototype Pollution.
The function defaultsDeep could be tricked into adding or modifying properties of Object.prototype using a constructor payload.
> [DDW-910] Upgrade lodash

- CHANGELOG.md
- source/features/stake-pools/components/StakePoolsSearch.scss
- source/features/stake-pools/components/StakePoolsSearch.tsx
- source/features/widgets/search/components/Search.tsx
- source/pages/index.tsx
- stories/pages.stories.tsx
As a developer, I want to re-use components as much as possible
At the moment, the Stake Pools page is using a generic Input component for the search. We need to integrate the Cardano Explorer Search component once DDW-935 is done.
* Go to the [`Stake Pools Page`](https://deploy-preview-33--cardano-explorer.netlify.com/?path=/story/pages--stake-pools-page) > Click the `Yes, show unmoderated content` button.
> [DDW-949] Integrate the Search component into the Stake Pools page

- CHANGELOG.md
- source/styles/resources/variables-themes/variables-theme-mainnet.scss
This PR adds missing SCSS variables in the mainnet theme:
```diff
@@ -3,15 +3,15 @@
* Variables for the `mainnet` theme.
*
*/
-$transparent-color: transparent;
+$dotted-separator-color: #36395d;
+$error-color: #eb2256;
+$footer-text-color: rgba(31, 193, 195, 0.3);
$primary-highlight-color: #1fc1c3;
$primary-highlight-color-hover: #1db0b3;
$primary-highlight-color-press: #1aa1a3;
-$secondary-highlight-color: #709cf0;
-$secondary-half-color: rgba(112, 156, 240, 0.5);
$secondary-color: rgba(112, 156, 240, 0.3);
-$dotted-separator-color: #36395d;
-$footer-text-color: rgba(31, 193, 195, 0.3);
+$secondary-half-color: rgba(112, 156, 240, 0.5);
+$secondary-highlight-color: #709cf0;
$spinner-circle-background-color: conic-gradient(
rgba(31, 193, 195, 0),
rgba(31, 193, 195, 0.2) 21%,
@ -20,3 +20,4 …
```
> [DDW-1033] Add missing SCSS variables in the mainnet theme

- source/features/search/components/BlocksSearchResult.tsx
- source/features/search/components/EpochsSearchResult.tsx
- source/lib/Store.ts
The problem we observed was that the search didn't 
work when you entered anything in the search bar 
and redirected to the search page. But in reality 
it was a race condition problem: the search 
component triggered the search in its render 
function and not using useEffect - which resulted 
in the action sometimes being dispatched before 
the search store was started (and thus the action 
was not handled)
> [DDW-1034] Trigger searches after component rendered

- CHANGELOG.md
- docker-compose.yml
- generated/typings/graphql-schema.d.ts
- next.config.js
- schema.graphql
- source/environment.ts
- source/features/blocks/api/BlockDetails.graphql
- source/features/blocks/api/BlockOverview.graphql
- source/features/blocks/api/transformers.ts
- source/features/epochs/api/EpochOverview.graphql
- source/features/epochs/api/transformers.ts
- source/features/epochs/specs/epochs.spec.ts
- source/features/network-info/store.ts
- source/features/search/specs/searchForEpochByNumber.spec.ts
- source/features/search/specs/searchForTransactionById.spec.ts
- source/features/transactions/api/transformers.ts
- source/lib/unit-converters.ts
Also some fixes:
- Includes block creator
- Scopes Epoch blocks count to exclude EBBs and the genesis, which in this context are not important.
- Lovelaces converted to Ada
- Changelog has been cleared, as the changes are only relevant post release.
**Edit:** Updates the lodash webpack plugin config to enable deep property path selection, cleaning up the mess of guards
> Chore/cardano graphql 0.3.0 upgrade

- source/features/blocks/ui/BlocksBrowser.tsx
- source/features/blocks/ui/LatestBlocks.tsx
- source/features/epochs/ui/EpochsBrowser.tsx
- source/features/epochs/ui/LatestEpochs.tsx
- source/features/search/ui/EpochsSearchResult.tsx
- source/widgets/browsing/BrowseInRange.tsx
This PR fixes a couple of issues with the browsing implementation:
- Handle invalid `upper` params correctly
- No redirect on invalid / incomplete params (just interpret best as possible), results in proper browser navigation support.
- Changes the default number of epochs and blocks to 20 and increase max to 50.
> Fixes #123 - improve browsing params handling

- package.json
- source/features/address/api/transformers.ts
- source/features/search/ui/SearchBar.tsx
- source/features/transactions/api/transformers.ts
- yarn.lock
Upgrade to cardano-js 0.3.0, adding the specificity of Cardano era to determine address format validity
> chore/cardano-js 0.3.0

- source/features/blocks/ui/BlockList.scss
- source/features/blocks/ui/BlockList.tsx
- source/features/search/ui/EpochsSearchResult.tsx
- source/widgets/table/Table.tsx
- source/widgets/table/TableBodyRow.scss
- source/widgets/table/TableBodyRow.tsx
This PR removes the links to the epoch in the Block list when viewing an epoch search result:
> Do not link to search result epoch in block list

- source/features/transactions/components/TransactionInfo.scss
This PR fixes #114 fixes transaction info component layout for smaller screens
Screenshots
> Issue- 114 Fix transaction info component

- source/features/epochs/store.ts
lastFetchedAtBlockHeight was never set on the epochs store and that’s why the store kept fetching the latest epochs endlessly (only getEpochsInRangeQuery.isExecuting was the „slow down“ factor, thats why it didnt surface against mainnet)
> Fix check for fetching latest epochs

- package.json
- source/features/outdated-browser/BrowserUpdate.tsx
- yarn.lock
This PR fixes #162 by upgrading the `browser-update` package and improves the browser detection to work with negative offsets, so we don't have to maintain the latest browser versions ourself.
> [issue-162] Update and fix browser update setup

- .storybook/webpack.config.js
- package.json
- source/widgets/layout/Header.tsx
- source/widgets/layout/Layout.scss
- stories/header.stories.tsx
- stories/support/ThemeDecorator.tsx
- stories/support/global.scss
- yarn.lock
This PR fixes #170 and solves some issues with `Link` component being used outside of Next.js pages by upgrading to the latest canary version as discussed here: https://stackoverflow.com/questions/59712474/set-up-storybook-to-work-with-next-jss-link-tag
> [issue-170] Fix broken storybook after css refactor

- source/features/errors/PageNotFoundError.tsx
- source/widgets/layout/Footer.tsx
This fixes an known limitation of the `next/Link` component that throws a warning when you use it with external URLs - the reason is that the `<Link>` component in Next.js is special as it pre-loads the contents of the linked page (which doesn't work for external pages)
> Fix: Dont use external urls with next.js Link

- source/features/blocks/ui/BlockList.module.scss
- source/features/blocks/ui/BlocksBrowser.module.scss
- source/features/blocks/ui/BlocksBrowser.tsx
- source/features/blocks/ui/LatestBlocks.module.scss
- source/features/blocks/ui/LatestBlocks.tsx
- source/features/epochs/ui/EpochsBrowser.module.scss
- source/features/epochs/ui/EpochsBrowser.tsx
- source/features/epochs/ui/LatestEpochs.module.scss
- source/features/epochs/ui/LatestEpochs.tsx
- source/features/landing-page/LandingPage.module.scss
- source/features/landing-page/LandingPage.tsx
- source/features/search/ui/AddressSearchResult.module.scss
- source/features/search/ui/AddressSearchResult.tsx
- source/features/search/ui/BlockSearchResult.module.scss
- source/features/search/ui/BlockSearchResult.tsx
- source/features/search/ui/EpochsSearchResult.module.scss
- source/features/search/ui/EpochsSearchResult.tsx
- source/features/search/ui/TransactionSearchResult.tsx
- source/pages/_app.module.scss
- source/pages/_app.tsx
- source/widgets/loading-spinner/LoadingSpinner.module.scss
- source/widgets/loading-spinner/LoadingSpinner.tsx
**PLEASE NOTE**: This PR is based on #219, so please merge this PR *afterwards*
This PR fixes #193 
- Includes the search bar in the static part of the landing page
- Adjusts the margin for various loading spinners in the app to visualize roughly the space that will be taken by the loaded content.
> [issue-193] Improve static rendering of landing page and general loading state consistency

- source/widgets/language-switcher/LanguageSwitcher.module.scss
Fixes #226 by adding an opaque background for the language switch options
> [issue-226] Add opaque bg to language options

- source/features/address/helpers.ts
- source/features/blocks/helpers.ts
- source/features/blocks/ui/BlockList.module.scss
- source/features/blocks/ui/BlockList.tsx
- source/features/blocks/ui/BlockSummary.tsx
- source/features/blocks/ui/LatestBlocks.tsx
- source/features/epochs/helpers.ts
- source/features/epochs/ui/EpochList.module.scss
- source/features/epochs/ui/EpochList.tsx
- source/features/epochs/ui/LatestEpochs.tsx
- source/features/errors/PageNotFoundError.tsx
- source/features/navigation/ui/LocalizedLink.module.scss
- source/features/navigation/ui/LocalizedLink.tsx
- source/features/search/ui/TransactionSearchResult.tsx
- source/features/stake-pools/components/UnmoderatedDataWarning.tsx
- source/features/transactions/components/TransactionInfo.module.scss
- source/features/transactions/components/TransactionInfo.tsx
- source/features/transactions/components/TransactionList.tsx
- source/features/transactions/helpers.ts
- source/widgets/decorators/ShowMoreButtonDecorator.module.scss
- source/widgets/decorators/ShowMoreButtonDecorator.tsx
- source/widgets/layout/Header.tsx
- stories/blocks.stories.tsx
Fixes #229 by refactoring all internal navigation to use `<LocalizedLink>`, which creates a real (<a> tag) link instead of relying on internal routing (which is less flexible for the user)
> [issue-229] Use real links for any navigation

- source/features/blocks/ui/BlocksBrowser.tsx
As discussed in #216 the intended UX is to browse blocks like they are continously written into a notebook, with the last page being appended to.
> [issue-216] Reverse list in blocks browsers

- source/features/blocks/ui/BlocksBrowser.tsx
- source/widgets/browsing/NavigationPagination.tsx
Fixes #241 by showing the loading state of the block list when browsing manually between pages.
> [issue-241] Show loading state for manual browsing

- source/features/i18n/translations/de.json
- source/features/i18n/translations/en.json
- source/features/i18n/translations/ja.json
- source/features/search/ui/pages/NoSearchResultPage.tsx
[issue 249] - Adding missing translations for No results page
> [issue 249] - Adding missing translations for No results page

- source/features/blocks/api/transformers.ts
- source/features/blocks/store.ts
- source/features/blocks/ui/BlocksBrowser.tsx
- source/features/epochs/store.ts
- source/features/search/store.ts
- source/features/transactions/store.ts
- source/lib/AbortablePromise.ts
- source/lib/graphql/GraphQLRequest.ts
- source/lib/mobx/react.ts
- source/lib/types.ts
Fixes #268 by simplifying the blocks browser render logic and debouncing the browse query (to avoid unnecessary calls when switching pages rapidly). This also reduces the executed queries to a minimum:
- One query immediately at first render
- Debounced query for page changes (query triggered after 400ms after last click)
- On the last page: one query after each block height / total items change (to support the trailing feature)
> [issue-268] Simplify and improve blocks browser

- source/features/transactions/components/TransactionInfo.module.scss
- source/features/transactions/components/TransactionInfo.tsx
This PR fixes the display of transaction inputs and ADA values to be in line with the design spec:
> [issue-294] Fix tx display of in and output values

- .graphqlconfig
- codegen.yml
- package.json
- source/config/jest.config.ts
- source/features/blocks/ui/BlockList.tsx
- source/features/blocks/ui/BlockSummary.tsx
- source/features/epochs/ui/EpochList.tsx
- source/features/epochs/ui/EpochSummary.tsx
- source/features/network-info/api/cardanoDynamic.graphql
- source/features/network-info/api/cardanoStatic.graphql
- source/features/network-info/specs/networkInfo.spec.ts
- source/features/network-info/store.ts
- source/features/search/specs/searchForBlockById.spec.ts
- source/features/stake-pools/components/StakePoolTooltip.tsx
- source/features/transactions/components/TransactionInfo.tsx
- yarn.lock
- Cardano GraphQL now returns dates as [ISO 3339](https://tools.ietf.org/html/rfc3339), whereas previously it just passed through the UTC string from the DB. The previous behaviour of `new Date(startDate)` would produce the desired outcome, but only for lack of additional meta for it to know any better. When calling `new Date(isoString)`, local server time is produced, so we need to specify a shift to UTC when applying it in the UI.
- Also accesses new `Cardano.tip` and `Cardano.slotsPerEpoch` to support Shelley networks and simplify the query.
- Also adds .graphqlconfig pointing at the package schema
> Update to conform with Cardano GraphQL 1.0.0-rc.13 changes

- source/features/blocks/api/transformers.ts
- source/features/search/specs/searchForBlockById.spec.ts
Simplifies the logic relating to the formatting of slot leader descriptions, fixing a bug with the software running in the Shelley era
> fix: Hardens the slot leader formatting

- CHANGELOG.md
- package.json
- source/features/epochs/api/EpochOverview.graphql
- source/features/epochs/api/transformers.ts
- source/features/network-info/specs/networkInfo.spec.ts
- source/features/network-info/store.ts
Fetches the most recent block in the epoch, and checks if there is a
protocolVersion. If so, the shelley genesis epochLength is used, else
default to 21600
> fix: Detect era to accurately display slot length

- source/features/epochs/ui/EpochList.module.scss
- source/features/epochs/ui/EpochList.tsx
- source/features/i18n/translations/de.json
- source/features/i18n/translations/en.json
- source/features/i18n/translations/ja.json
This PR fixes #335 by splitting slots and blocks counts into separate columns in the epoch list table. This should reduce potential confusion about Shelley slots & and blocks not necessarily matching in numbers (and thus assuming bad performance of the Cardano network, although these metrics are not valid indicators anymore):
> [issue-335] Split slots & blocks into separate columns

- next.config.js
- package.json
- source/environment.ts
- source/widgets/layout/Footer.module.scss
- source/widgets/layout/Footer.tsx
Displays the software version in the footer, and replaces the hard-coded
link with the `package.json` homepage value. This information is very 
useful for the release and ops process.
https://deploy-preview-348--cardano-explorer-mainnet.netlify.app/
> feat: Add package.json version to footer

- package.json
- yarn.lock
The latest react-polymorph version removed the deprecated postinstall-build package.
You can see the related changes here:
https://github.com/input-output-hk/react-polymorph/pull/146
> [SRE-134] Update to latest react-polymorph

- source/features/i18n/translations/de.json
- source/features/i18n/translations/en.json
- source/features/i18n/translations/ja.json
- source/features/transactions/api/TransactionDetails.graphql
- source/features/transactions/api/transformers.ts
- source/features/transactions/components/TransactionInfo.tsx
- source/features/transactions/types.ts
Shows Deposit or Deposit Reclaim in the `TransactionInfo` when present in
transaction
Closes #353
> feat: show deposits and reclaims when present in transaction

- source/features/blocks/api/BlockOverview.graphql
- source/features/blocks/api/transformers.ts
Closes #355
when a block is created by a stake pool, the pool hash is now used. BFT
nodes still use the slot leader reference
> feat: use stake pool hash over slot leader reference

- CHANGELOG.md
- source/features/blocks/api/BlockOverview.graphql
- source/features/blocks/api/transformers.ts
This reverts commit 0f345dd2
This change exposes a potential issue with the GraphQL client library, which is not yet fully understood, however should not hold up the release. We will revisit later with the larger update for stake pool information
> Revert "feat: use stake pool hash over slot leader reference"

- source/features/transactions/components/TransactionTokenList.tsx
There's a stray character in the list component:
> fix: remove stray acute character

- source/environment.ts
- source/features/transactions/api/README.md
- source/features/transactions/api/transactionMetadata.graphql
Accepts an array of transaction hashes, returns just the metadata
and reflects the hash.
> feature: add query to support fetching transaction metadata
