- .storybook/webpack.config.js
- stories/support/ThemeDecorator.tsx
This PR fixes Storybook, which is broken due to PR #14.
> [DDW-923] Fix Storybook configuration

- README.md
- docker-compose.yml
- generated/typings/graphql-schema.d.ts
- source/features/shared/search/graphql/getBlocks.graphql
- utils/start_dependencies.sh
Also updates the single implemented query. The `schema.graphql` in the root has not changed from the initial commit, so am considering this out of scope.
> Pin Cardano GraphQL to 0.1.6

- source/features/stake-pools/components/StakePools.tsx
- source/pages/stake-pools.tsx
This PR fixes merging issues from Stake Pools PR
> [DDW-948] Fix merging issues from Stake Pools PR

- CHANGELOG.md
- yarn.lock
As a developer, I want the project's dependencies to not present any vulnerability.
We need to fix the [dependencies vulnerabilities](https://github.com/input-output-hk/cardano-explorer-app/network/alerts).
* [QA Thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1571316924178400)
> [DDW-951] Fix dependencies vulnerabilities

- CHANGELOG.md
- source/features/transactions/components/TransactionList.tsx
- source/features/widgets/container/components/Container.scss
- source/features/widgets/footer/components/Footer.scss
- source/features/widgets/header/components/Header.scss
- source/features/widgets/header/components/Header.tsx
- source/features/widgets/pagination/components/Pagination.scss
- source/features/widgets/pagination/components/Pagination.tsx
- source/pages/address.scss
- source/pages/address.tsx
- stories/transactions.stories.tsx
This PR implemented pagination component.
[YouTrack Ticket](https://iohk.myjetbrains.com/youtrack/issue/DDW-937)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1571658206188000)
> [DDW-937]: Implement pagination component

- CHANGELOG.md
- source/features/epochs/components/StakeDistribution.scss
- source/features/epochs/components/StakeDistribution.tsx
- source/features/epochs/components/StakeDistributionRow.scss
- source/features/epochs/components/StakeDistributionRow.tsx
- source/pages/epoch.scss
- source/pages/epoch.tsx
- stories/epochs.stories.tsx
This PR implemented pagination component.
[YouTrack Ticket](https://iohk.myjetbrains.com/youtrack/issue/DDW-915)
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1571695062195200)
> [DDW-915] Add stake distribution table to the current epoch page

- source/config/jest.config.ts
Adds a longer timeout in the only place it's needed
> Reduce global timeout for tests

- Jenkinsfile
- README.md
- deploy/byron_incentivized_testnet.js
- deploy/byron_staging.js
- deploy/index.js
- deploy/jormungandr_incentivized_testnet.js
- deploy/upload.js
- package.json
- yarn.lock
Continuous delivery to S3 on merge to develop.
Currently supports deploying:
- Byron Mainnet (in a staging format)
- Byron incentivized testnet (however the is not yet a backend for this)
> Continuous delivery s3

- source/features/search/store.ts
The switch to MobX strict mode happened in a branch that was later merged here.
> Wrap address search result in action runner

- source/widgets/layout/Layout.tsx
> Fix broken styles loading in next.js dev mode

- source/features/search/api/searchForAddress.graphql
- source/features/search/specs/helpers/exampleAddressData.ts
> Match transactions in aggregate query for inputs too

- package.json
- source/widgets/layout/Footer.tsx
Updates the content for legal compliance, styling to be handled separately
> Chore: Footer content legal compliance, and conformance with staking website links

- next.config.js
- source/environment.ts
- source/features/network-info/api/cardanoStatic.graphql
- source/features/network-info/store.ts
Fixes #146 by throwing an error if the api and environment network are not matching.
> [issue-146] Throw on api / env network mismatch

- .browserslistrc
- package.json
Fixes the supported browsers list and renames the bundle analyze script
> Fix supported browsers list

- source/constants.ts
- source/styles/theme/theme.tsx
- source/widgets/layout/Header.module.scss
- source/widgets/layout/Header.tsx
- stories/epochs.stories.tsx
> Remove Incentivized Testnet theme

- .storybook/webpack.config.js
- package.json
We had an issue with storybook font loading through webpack configuration. This PR fixes that.
> Fixing storybook font loading

- source/features/search/ui/Search.module.scss
- source/widgets/layout/Header.module.scss
Fix/issue 201 - Search bar and button style
> Fix/issue 201 - Search bar and button style

- source/widgets/layout/Header.module.scss
- source/widgets/layout/Header.tsx
Fixing issue 199 - Header text is not a home link target
> Fixing issue 199 - Header text is not a home link target

- source/widgets/layout/Footer.module.scss
> Fixing issue 198 - Footer fixes

- source/widgets/browsing/Pagination.module.scss
- source/widgets/browsing/Pagination.tsx
Fixes #195 - Pagination arrow hover styling
> Fixing issue 195 - Pagination arrow hover styling

- source/widgets/layout/Header.module.scss
- source/widgets/layout/Header.tsx
Fixes #196 - Erroneous subheading on homepage, invalid styling of the downward arrow element
> Fixing issue 196 - Erroneous subheading on homepage, invalid styling of the downward arrow element

- source/features/outdated-browser/OutdatedBrowser.module.scss
- source/pages/outdated-browser.tsx
- stories/outdated-browser.stories.tsx
Fixes #200 - Outdated Browser page styling and missing footer
> Fixing issue 200 - Outdated Browser page styling and missing footer

- source/features/search/ui/Search.module.scss
- source/features/search/ui/Search.tsx
- source/styles/theme/theme.tsx
> Fixing issue 197 - Component misalignment

- source/features/search/ui/Search.module.scss
Search button looses highlighting effect if cursor if moved out while button still pressed
> Search button looses highlighting effect if cursor if moved out while button still pressed

- source/features/search/ui/Search.tsx
This PR fixes #194 - prevent submitting empty values for searches.
> [issue-194] Prevent searching for empty values

- source/widgets/layout/Footer.module.scss
- source/widgets/layout/Footer.tsx
Cardano Explorer. Highlighting effect for Social Media Icons
> Cardano Explorer. Highlighting effect for Social Media Icons

- source/features/i18n/translations/404/ja.json
- source/features/i18n/translations/ja.json
[issue 248] - Explorer's Tab is missing key when Japanese is selected
> [issue 248] - Explorer's Tab is missing key when Japanese is selected

- source/features/epochs/ui/EpochsBrowser.tsx
> [issue-265] Fix order of epochs browser

- source/features/i18n/translations/de.json
- source/features/i18n/translations/en.json
- source/features/i18n/translations/ja.json
> [issue-264] Do not translate the locale picker

- source/features/blocks/ui/BlockList.tsx
- source/features/blocks/ui/BlocksBrowser.tsx
Remove Epoch/Slot Links on the opened page
Issue: #271
> [issue 271] - Remove Epoch/Slot Links on the opened page

- .storybook/config.js
- source/features/outdated-browser/OutdatedBrowser.tsx
- source/public/assets/images/arrow-beginning.svg
- source/public/assets/images/arrow-end.svg
- source/styles/global/reset.scss
- source/widgets/browsing/Pagination.module.scss
- source/widgets/browsing/Pagination.tsx
- source/widgets/language-switcher/LanguageSwitcher.tsx
- stories/address.stories.tsx
- stories/blocks.stories.tsx
- stories/epochs.stories.tsx
- stories/error.stories.tsx
- stories/footer.stories.tsx
- stories/header.stories.tsx
- stories/language-switcher.stories.tsx
- stories/outdated-browser.stories.tsx
- stories/support/I18nDecorator.tsx
- tslint.json
[issue-272] - Pagination Improvement
Fixes issue #272
> [issue-272] - Pagination Improvement

- source/features/navigation/store.ts
This improves the GA tracking to include full URL instead of just pathname
> [DDW-118] Track full url for any page view

- source/pages/_app.tsx
This simply enables the preact dev tools in development
> Enable preact debug in dev mode

- source/features/i18n/translations/de.json
- source/features/i18n/translations/en.json
- source/features/i18n/translations/ja.json
- source/features/search/ui/SearchSuggestions.tsx
> Missing JP translations

- package.json
- source/features/blocks/api/BlockDetails.graphql
- source/features/blocks/api/BlockOverview.graphql
- source/features/blocks/api/transformers.ts
- source/features/search/api/searchById.graphql
- source/features/search/api/searchForTransactionById.graphql
- source/features/search/specs/helpers/exampleAddressData.ts
- source/features/transactions/api/TransactionDetails.graphql
- source/features/transactions/api/getBlockTransactions.graphql
- source/features/transactions/api/transformers.ts
- yarn.lock
Makes minimal changes to conform with upstream API change ahead of Cardano GraphQL 1.0.0
> Update to conform with Cardano GraphQL breaking changes

- source/environment.ts
- source/features/blocks/ui/BlockList.tsx
- source/features/epochs/ui/EpochList.tsx
- source/features/i18n/store.ts
- source/features/outdated-browser/OutdatedBrowser.tsx
- source/features/search/ui/Search.tsx
- source/features/search/ui/SearchBar.tsx
- source/features/transactions/api/transformers.ts
- source/lib/AbortablePromise.ts
- source/lib/Action.ts
- source/lib/ActionBinding.ts
- source/lib/StatefulRequest.ts
- source/lib/Store.ts
- source/lib/colors.ts
- source/lib/enums.ts
- source/lib/logging.ts
- source/lib/mobx/Reaction.ts
- source/styles/theme/CssVariablesProvider.tsx
- source/widgets/browsing/Pagination.tsx
- source/widgets/language-switcher/LanguageSwitcher.tsx
- source/widgets/layout/Layout.tsx
- source/widgets/table/TableBody.tsx
- stories/epochs.stories.tsx
- stories/search.stories.tsx
- stories/stake-pools.stories.tsx
This PR simply fixes the currently broken prettier formatting (which fails CI on other PRs).
> Fix prettier formatting

- source/features/i18n/translations/de.json
- source/features/i18n/translations/en.json
- source/features/i18n/translations/ja.json
- source/widgets/layout/Footer.tsx
This PR fixes #302 by cleaning up footer links.
> [issue-302] Cleanup footer links

- next.config.js
- source/features/address/config.ts
- source/features/blocks/config.ts
- source/features/epochs/config.ts
- source/features/errors/PageNotFoundError.tsx
- source/features/search/config.ts
- source/features/stake-pools/components/UnmoderatedDataWarning.tsx
- source/features/transactions/config.ts
- source/widgets/layout/Header.tsx
This PR fixes #232 by removing any trailing slashes for our routes (they are not necessary anyway)
@rhyslbw I'm not sure how this will impact analytics though :( it might be the case that all statistics will be off due to the missing trailing slashes after this is merged.
> [issue-232] Fix strange reloading in dev env

- .github/workflows/tests.yml
- package.json
- source/features/blocks/api/BlockOverview.graphql
- source/features/blocks/api/transformers.ts
- source/features/network-info/api/cardanoDynamic.graphql
- source/features/network-info/store.ts
- source/features/transactions/api/transformers.ts
- source/features/transactions/components/TransactionInfo.tsx
- source/features/transactions/types.ts
- yarn.lock
- restores slotInEpoch
- logic to determine era now based on protocolVersion
> chore: minor changes to support cardano-graphql 2.0.0

- source/features/blocks/api/transformers.ts
- source/features/blocks/ui/BlockList.tsx
- source/features/blocks/ui/BlockSummary.tsx
- source/features/epochs/api/transformers.ts
- source/features/epochs/ui/EpochList.tsx
- source/features/epochs/ui/EpochSummary.tsx
- source/features/stake-pools/components/StakePoolTooltip.tsx
- source/features/transactions/components/TransactionInfo.tsx
This PR simply fixes prettier formatting
> Fixes prettier formatting

- nix/packages.nix
- release.nix
- Align with terminology changes in cardano-graphql for allow/deny
- include/exclude
> chore: allow/deny, include/exclude terminology

- default.nix
- nix/cardano-explorer-app.nix
- nix/packages.nix
- nix/pkgs.nix
- nix/sources.json
- nix/static.nix
- nix/yarn2nix.nix
- release.nix
- shell.nix
Switch Nix services to using offline cache in step with the project
> [SRE-134] switch to offline cache

- source/features/blocks/ui/BlockSummary.tsx
> fix: only show merkel root if present

- source/features/search/ui/TransactionSearchResult.tsx
- source/features/transactions/components/TransactionInfo.tsx
> "0" displayed on a line after Transaction Fee / Total Output

- source/features/transactions/components/TransactionInfo.module.scss
- source/features/transactions/components/TransactionTokenList.module.scss
Fixes https://github.com/input-output-hk/cardano-explorer-app/issues/389, an issue where the token lists wouldn't be displayed on mobile
> fix: styles on token lists

- source/features/address/ui/AddressSummary.tsx
- source/features/transactions/components/TransactionInfo.tsx
- source/features/transactions/components/TransactionTokenList.tsx
- source/widgets/tooltip/Tooltip.module.scss
- source/widgets/tooltip/Tooltip.tsx
> EX-1404 - fix: tooltip position on small screen size
